In [1]:
import pandas as pd
import numpy as np

# wczytanie danych
df = pd.read_csv("../data/raw/new_york_real_estate_2026_final.csv")

# podstawowe informacje
print("Shape:", df.shape)

df.head()

Shape: (8273, 11)

,type,sub_type,text,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage
0,single_family,NaN,No description provided.,325000.0,1252.0,2.0,3.0,2.0,2.0,2.0,1.0
1,single_family,NaN,Shortsale.,308000.0,NaN,NaN,4.0,4.0,4.0,4.0,NaN
2,multi_family,NaN,Discover an exceptional investment opportunity...,799999.0,NaN,NaN,11.0,6.0,7.0,7.0,1.0
3,single_family,NaN,Classic Cape Cod with 4 bedrooms and 2 full ba...,189900.0,1400.0,3.0,4.0,2.0,2.0,2.0,2.0
4,single_family,NaN,"Spacious 4-bedroom, 2.5-bath two-story home of...",204900.0,2074.0,2.0,4.0,2.0,2.0,2.0,2.0

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8273 entries, 0 to 8272
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   type             8273 non-null   object
 1   sub_type         1898 non-null   object
 2   text             8273 non-null   object
 3   listPrice        8273 non-null   float64
 4   sqft             7167 non-null   float64
 5   stories          4097 non-null   float64
 6   beds             7933 non-null   float64
 7   baths            7882 non-null   float64
 8   baths_full       7846 non-null   float64
 9   baths_full_calc  7855 non-null   float64
 10  garage           4062 non-null   float64
dtypes: float64(8), object(3)
memory usage: 711.1+ KB

In [3]:
df.describe()

,listPrice,sqft,stories,beds,baths,baths_full,baths_full_calc,garage
count,8.273000e+03,7.167000e+03,4097.000000,7933.000000,7882.000000,7846.000000,7855.000000,4062.000000
mean,1.094366e+06,2.330063e+03,3.247742,3.439178,2.481604,2.104384,2.117632,2.870261
std,2.542967e+06,1.773651e+04,6.315546,2.058459,1.602000,1.350849,1.353833,30.457501
min,1.000000e+00,1.000000e+00,1.000000,0.000000,0.000000,1.000000,1.000000,1.000000
25%,2.500000e+05,1.210000e+03,2.000000,2.000000,2.000000,1.000000,1.000000,1.000000
50%,5.299000e+05,1.680000e+03,2.000000,3.000000,2.000000,2.000000,2.000000,2.000000
75%,9.490000e+05,2.400000e+03,2.000000,4.000000,3.000000,2.000000,2.000000,2.000000
max,8.000000e+07,1.481040e+06,96.000000,100.000000,40.000000,30.000000,30.000000,1440.000000

In [4]:
missing = df.isnull().sum().sort_values(ascending=False)
missing

sub_type           6375
garage             4211
stories            4176
sqft               1106
baths_full          427
baths_full_calc     418
baths               391
beds                340
type                  0
text                  0
listPrice             0
dtype: int64

In [5]:
(df.isnull().mean()*100).sort_values(ascending=False)

sub_type           77.057899
garage             50.900520
stories            50.477457
sqft               13.368790
baths_full          5.161368
baths_full_calc     5.052581
baths               4.726218
beds                4.109755
type                0.000000
text                0.000000
listPrice           0.000000
dtype: float64